### ISSUE TITLE
snmp无法获取数据

### ISSUE THREAD

**Issue by siye1103** [hema0320/template_emerson_ita2#1]
snmp无法获取数据
![image](https://user-images.githubusercontent.com/32047486/230330354-56db7827-1b7b-407e-9c6b-5e593f3173a8.png)

**Comment by hema0320** [comment]
改模板还没最终完成，不过相应的OID已经从UPS系统里摘出来了。如果急的话可以自己尝试修改。

**Comment by hema0320** [comment]
> snmp无法获取数据 ![image](https://user-images.githubusercontent.com/32047486/230330354-56db7827-1b7b-407e-9c6b-5e593f3173a8.png)

模板已更新可以测试一下看看有什么问题没有
